package com.fruitshop.springbootmybaties.dataobject;

import java.util.Date;

public class CartDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.user_id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.item_id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.amount
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.price
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.total_price
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.create_time
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.update_time
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_info.status
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.id
     *
     * @return the value of cart_info.id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.id
     *
     * @param id the value for cart_info.id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.user_id
     *
     * @return the value of cart_info.user_id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.user_id
     *
     * @param userId the value for cart_info.user_id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.item_id
     *
     * @return the value of cart_info.item_id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.item_id
     *
     * @param itemId the value for cart_info.item_id
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.amount
     *
     * @return the value of cart_info.amount
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.amount
     *
     * @param amount the value for cart_info.amount
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.price
     *
     * @return the value of cart_info.price
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.price
     *
     * @param price the value for cart_info.price
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.total_price
     *
     * @return the value of cart_info.total_price
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.total_price
     *
     * @param totalPrice the value for cart_info.total_price
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.create_time
     *
     * @return the value of cart_info.create_time
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.create_time
     *
     * @param createTime the value for cart_info.create_time
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.update_time
     *
     * @return the value of cart_info.update_time
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.update_time
     *
     * @param updateTime the value for cart_info.update_time
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_info.status
     *
     * @return the value of cart_info.status
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_info.status
     *
     * @param status the value for cart_info.status
     *
     * @mbg.generated Tue Feb 11 12:35:36 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}