package com.fruitshop.springbootmybaties.dataobject;

import java.util.Date;

public class LogisticsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.id
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.address
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.order_id
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logistics_info.create_time
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.id
     *
     * @return the value of logistics_info.id
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.id
     *
     * @param id the value for logistics_info.id
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.address
     *
     * @return the value of logistics_info.address
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.address
     *
     * @param address the value for logistics_info.address
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.order_id
     *
     * @return the value of logistics_info.order_id
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.order_id
     *
     * @param orderId the value for logistics_info.order_id
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logistics_info.create_time
     *
     * @return the value of logistics_info.create_time
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logistics_info.create_time
     *
     * @param createTime the value for logistics_info.create_time
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}