package com.fruitshop.springbootmybaties.dataobject;

import java.util.Date;

public class StorePasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_password.id
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_password.store_id
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_password.encrpt_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    private String encrptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_password.create_time
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store_password.update_time
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_password.id
     *
     * @return the value of store_password.id
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_password.id
     *
     * @param id the value for store_password.id
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_password.store_id
     *
     * @return the value of store_password.store_id
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_password.store_id
     *
     * @param storeId the value for store_password.store_id
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_password.encrpt_password
     *
     * @return the value of store_password.encrpt_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public String getEncrptPassword() {
        return encrptPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_password.encrpt_password
     *
     * @param encrptPassword the value for store_password.encrpt_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public void setEncrptPassword(String encrptPassword) {
        this.encrptPassword = encrptPassword == null ? null : encrptPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_password.create_time
     *
     * @return the value of store_password.create_time
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_password.create_time
     *
     * @param createTime the value for store_password.create_time
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store_password.update_time
     *
     * @return the value of store_password.update_time
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store_password.update_time
     *
     * @param updateTime the value for store_password.update_time
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}