package com.fruitshop.springbootmybaties.dao;

import com.fruitshop.springbootmybaties.dataobject.LogisticsDO;
import org.springframework.stereotype.Repository;

@Repository
public interface LogisticsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    int insert(LogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    int insertSelective(LogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    LogisticsDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    int updateByPrimaryKeySelective(LogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics_info
     *
     * @mbg.generated Sun Feb 09 16:06:30 CST 2020
     */
    int updateByPrimaryKey(LogisticsDO record);
}