package com.fruitshop.springbootmybaties.dao;

import com.fruitshop.springbootmybaties.dataobject.OrderDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 09 15:39:06 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 09 15:39:06 CST 2020
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 09 15:39:06 CST 2020
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 09 15:39:06 CST 2020
     */
    OrderDO selectByPrimaryKey(String id);

    List<OrderDO> selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 09 15:39:06 CST 2020
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Sun Feb 09 15:39:06 CST 2020
     */
    int updateByPrimaryKey(OrderDO record);

    int cancelOrder(String id);
}