package com.fruitshop.springbootmybaties.dao;

import com.fruitshop.springbootmybaties.dataobject.StorePasswordDO;
import org.springframework.stereotype.Repository;

@Repository
public interface StorePasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int insert(StorePasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int insertSelective(StorePasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    StorePasswordDO selectByPrimaryKey(Integer id);

    StorePasswordDO selectByStoreId(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int updateByPrimaryKeySelective(StorePasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_password
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int updateByPrimaryKey(StorePasswordDO record);
}