package com.fruitshop.springbootmybaties.dao;

import com.fruitshop.springbootmybaties.dataobject.StoreDO;
import org.springframework.stereotype.Repository;

@Repository
public interface StoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int insert(StoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int insertSelective(StoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    StoreDO selectByPrimaryKey(Integer id);

    StoreDO selectByTelphone(String telphone);

    StoreDO selectByStoreName(String storeName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int updateByPrimaryKeySelective(StoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_info
     *
     * @mbg.generated Mon Feb 10 18:46:43 CST 2020
     */
    int updateByPrimaryKey(StoreDO record);
}